### ISSUE TITLE
MDB Activation failure on startup

### ISSUE THREAD

**Issue by stephan-sch** [eurodyn/QLACK1#2]
On server start up and deployment of ares, following error did appear:
`08:14:27,771 ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0215: Failed to resume activity org.jboss.as.ejb3.component.messagedriven.MessageDrivenComponent$1@52e217ef. To resume normal operation it is recommended that you restart the server.: java.lang.RuntimeException: WFLYEJB0501: Failed to activate MDB AuditMDB
    at org.jboss.as.ejb3@7.2.7.GA-redhat-00004//org.jboss.as.ejb3.component.messagedriven.MessageDrivenComponent.activate(MessageDrivenComponent.java:279)
    at org.jboss.as.ejb3@7.2.7.GA-redhat-00004//org.jboss.as.ejb3.component.messagedriven.MessageDrivenComponent.access$300(MessageDrivenComponent.java:63)
    at org.jboss.as.ejb3@7.2.7.GA-redhat-00004//org.jboss.as.ejb3.component.messagedriven.MessageDrivenComponent$1.resume(MessageDrivenComponent.java:109)
    at org.jboss.as.server@6.0.24.Final-redhat-00001//org.jboss.as.server.suspend.SuspendController.resume(SuspendController.java:126)
    at org.jboss.as.server@6.0.24.Final-redhat-00001//org.jboss.as.server.ServerService.finishBoot(ServerService.java:420)
    at org.jboss.as.server@6.0.24.Final-redhat-00001//org.jboss.as.server.ServerService.boot(ServerService.java:388)
    at org.jboss.as.controller@6.0.24.Final-redhat-00001//org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:372)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.resource.spi.InvalidPropertyException: Invalid settings: Destination is mandatory.
    at org.apache.activemq.artemis.ra@2.9.0.redhat-00009//org.apache.activemq.artemis.ra.inflow.ActiveMQActivationValidationUtils.buildAndThrowExceptionIfNeeded(ActiveMQActivationValidationUtils.java:84)
    at org.apache.activemq.artemis.ra@2.9.0.redhat-00009//org.apache.activemq.artemis.ra.inflow.ActiveMQActivationValidationUtils.validate(ActiveMQActivationValidationUtils.java:72)
    at org.apache.activemq.artemis.ra@2.9.0.redhat-00009//org.apache.activemq.artemis.ra.inflow.ActiveMQActivationSpec.validate(ActiveMQActivationSpec.java:707)
    at org.jboss.ironjacamar.impl@1.4.20.Final-redhat-00001//org.jboss.jca.core.rar.EndpointImpl.activate(EndpointImpl.java:201)
    at org.jboss.as.ejb3@7.2.7.GA-redhat-00004//org.jboss.as.ejb3.component.messagedriven.MessageDrivenComponent.activate(MessageDrivenComponent.java:277)
    ... 7 more`

Current JMS entry in JBoss configuration:

` <jms-queue name="AuditQueue" entries="jms/AuditQueue"/>`

Change on AuditMessageBean  pushed. Please verify

**Comment by stephan-sch** [comment]
Issue resolved.
